2015-01-07 16:18:45,247 139864646162240 Inizialiazzazione completa
2015-01-07 16:19:05,254 139864578668288 Rivevuti 0 messages
2015-01-07 16:19:25,265 139864578668288 Rivevuti 0 messages
2015-01-07 16:19:37,720 139963037173568 Inizialiazzazione completa
2015-01-07 16:23:02,560 140332323108672 Inizialiazzazione completa
2015-01-07 16:23:22,568 140332255614720 Rivevuti 0 messages
2015-01-07 16:23:42,575 140332255614720 Rivevuti 0 messages
2015-01-07 16:24:02,582 140332255614720 Rivevuti 0 messages
2015-01-07 16:24:22,588 140332255614720 Rivevuti 0 messages
2015-01-07 16:24:42,595 140332255614720 Rivevuti 0 messages
2015-01-07 16:25:02,602 140332255614720 Rivevuti 0 messages
2015-01-07 16:26:11,401 140512417384256 Inizialiazzazione completa
2015-01-07 16:30:54,110 140012202346304 Inizialiazzazione completa
2015-01-07 16:31:14,116 140012129773312 Rivevuti 0 messages
2015-01-07 16:31:34,122 140012129773312 Rivevuti 0 messages
2015-01-07 16:31:54,127 140012129773312 Rivevuti 0 messages
2015-01-07 16:32:23,629 139892828071744 Inizialiazzazione completa
2015-01-07 16:32:43,637 139892755498752 Rivevuti 0 messages
2015-01-07 16:33:04,203 139907191158592 Inizialiazzazione completa
2015-01-07 16:33:29,446 140687370041152 Inizialiazzazione completa
2015-01-07 16:34:00,411 139972401928000 Inizialiazzazione completa
2015-01-07 16:34:14,360 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:34:14,572 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:34:14,771 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:34:19,978 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:34:20,418 139972329355008 Rivevuti 0 messages
2015-01-07 16:34:38,641 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:34:40,424 139972329355008 Rivevuti 0 messages
2015-01-07 16:35:00,430 139972329355008 Rivevuti 0 messages
2015-01-07 16:35:11,404 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:35:20,437 139972329355008 Rivevuti 0 messages
2015-01-07 16:35:40,443 139972329355008 Rivevuti 0 messages
2015-01-07 16:35:41,619 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:36:00,449 139972329355008 Rivevuti 0 messages
2015-01-07 16:36:20,464 139972329355008 Rivevuti 0 messages
2015-01-07 16:36:37,208 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:36:40,470 139972329355008 Rivevuti 0 messages
2015-01-07 16:36:45,559 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:36:45,656 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:36:45,850 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:36:46,161 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:36:51,361 139972401928000 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:37:00,476 139972329355008 Rivevuti 0 messages
2015-01-07 16:37:20,484 139972329355008 Rivevuti 0 messages
2015-01-07 16:37:54,190 139669668144960 Inizialiazzazione completa
2015-01-07 16:38:00,295 139669668144960 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 234, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 282, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1884, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1904, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 180, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'front_end_address'
2015-01-07 16:38:14,196 139669595571968 Rivevuti 0 messages
2015-01-07 16:40:23,850 139798845142848 Inizialiazzazione completa
2015-01-07 16:40:28,632 139798845142848 200 GET / (87.9.36.211) 12.06ms
2015-01-07 16:40:28,817 139798845142848 200 GET /static/bootstrap-tagsinput.css?v=c9b1c0b96cd68c758bd3a117cad18867 (87.9.36.211) 5.99ms
2015-01-07 16:40:28,823 139798845142848 200 GET /static/map.css?v=2bf80f98de30d87e63e501959e814ad4 (87.9.36.211) 0.90ms
2015-01-07 16:40:28,926 139798845142848 200 GET /static/map.js?v=d0073f367f323289714724f92a031503 (87.9.36.211) 1.13ms
2015-01-07 16:40:28,940 139798845142848 200 GET /static/utils.js?v=cd0f1b4f6a8e4f7e2e74dab914aed2da (87.9.36.211) 0.96ms
2015-01-07 16:40:29,052 139798845142848 200 GET /static/test.js?v=210467ddcdeed94432837a88a5503ae0 (87.9.36.211) 1.00ms
2015-01-07 16:40:29,078 139798845142848 200 GET /static/websocketHandler.js?v=4e1e47289ab84083f7043c9d6f480910 (87.9.36.211) 1.04ms
2015-01-07 16:40:29,091 139798845142848 200 GET /static/bootstrap-tagsinput.js?v=88614e8e5c7e99b1dbe3beab8b5e0557 (87.9.36.211) 1.11ms
2015-01-07 16:40:30,950 139798845142848 404 GET /favicon.ico (87.9.36.211) 8.17ms
2015-01-07 16:40:36,059 139798845142848 200 GET /imgs/map_pointer.png (87.9.36.211) 1.17ms
2015-01-07 16:40:43,858 139798772569856 Rivevuti 0 messages
2015-01-07 16:41:03,864 139798772569856 Rivevuti 0 messages
2015-01-07 16:41:23,870 139798772569856 Rivevuti 0 messages
2015-01-07 16:41:32,935 139795647805184 302 POST /register (87.9.36.211) 597.12ms
2015-01-07 16:41:33,058 139798845142848 200 GET / (87.9.36.211) 8.67ms
2015-01-07 16:41:43,877 139798772569856 Rivevuti 0 messages
2015-01-07 16:41:45,144 139795656197888 302 POST /login (87.9.36.211) 543.44ms
2015-01-07 16:41:45,263 139798845142848 200 GET / (87.9.36.211) 7.96ms
2015-01-07 16:41:49,154 139798845142848 302 GET /logout (87.9.36.211) 0.91ms
2015-01-07 16:41:49,273 139798845142848 200 GET / (87.9.36.211) 12.23ms
2015-01-07 16:42:03,883 139798772569856 Rivevuti 0 messages
